name       : vertex-gtk-theme
version    : 20150718
release    : 4
source     :
    - https://github.com/horst3180/Vertex-theme/archive/20150718.tar.gz : b947d7e975a101dbde902104102ee7b007cc2ed65133ad14e7ef1c1eeea17b4d
license    : GPL-3.0
summary    : Vertex Theme
description: |
    Vertex is a theme for GTK 3, GTK 2, Gnome-Shell and Cinnamon. It supports GTK 3 and GTK 2 based desktop environments like Gnome, Cinnamon, Mate, XFCE, Budgie, Pantheon, etc. Themes for the Browsers Chrome/Chromium and Firefox are included, too.
setup      : |
     ./autogen.sh $CONFOPTS \
         --disable-cinnamon \
         --disable-gnome-shell \
         --disable-metacity \
         --disable-unity \
         --disable-xfwm \
         --with-gnome=3.16
build      : |
    %make
install    : |
    %make_install
