name       : vertex-gtk-theme
version    : 20150425
release    : 2
source     :
    - https://github.com/horst3180/Vertex-theme/archive/20150425.tar.gz : be5e78c83195aed3784f32eae3d588e1ca242158ad1165167ffd47f891745045
license    : GPL-3.0
summary    : Vertex Theme
description: |
    Vertex is a theme for GTK 3, GTK 2, Gnome-Shell and Cinnamon. It supports GTK 3 and GTK 2 based desktop environments like Gnome, Cinnamon, Mate, XFCE, Budgie, Pantheon, etc. Themes for the Browsers Chrome/Chromium and Firefox are included, too.
setup      : |
    CONFIG_SHELL=/bin/bash \
                 ./autogen.sh --prefix=/usr \
                 --disable-cinnamon \
                 --disable-gnome-shell \
                 --disable-metacity \
                 --disable-unity \
                 --disable-xfwm \
                 --with-gnome=3.16
build      : |
    %make
install    : |
    %make_install
